name: Bug report
description: Create a report to help us improve.
labels:
  - "bug"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description:
        A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Screenshots / Live demo link
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste the github-stats link as markdown image
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ---
        ### FAQ (Snippet)

        #### Q: How to hide jupyter Notebook?

        **Ans:** `&hide=jupyter%20notebook`.

        #### Q: I could not figure out how to deploy on my own vercel instance

        **Ans:** Please check:
          - Docs: https://github.com/rstar327/github-stats/#deploy-on-your-own
          - YT tutorial by codeSTACKr: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107

        #### Q: How to count private stats?

        **Ans:** We can only count private commits & we cannot access any other private info of any users, so it's impossible. The only way is to deploy on your own instance & use your own PAT (Personal Access Token).
