name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  config:
    if: github.repository == 'rstar327/github-stats'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
